pages = Any["index.md",
"Exercises" => Any[
    "exercises/mtk_chemical_reaction.md",
    "exercises/stiffbio_uncertainty.md",
    "exercises/hybriddelay_pharmacokinetics.md",
    "exercises/dae_double_pendulum.md",
    "exercises/acausal_circuit.md",
    "exercises/performance_pde.md",
    "exercises/gsa_henon_heiles.md",
    "exercises/neural_sde.md",
    "exercises/dc_motor_control.md"],
"Selected Solutions" => Any[
    "solutions/mtk_chemical_reaction.md",
    "solutions/stiffbio_uncertainty.md",
    "solutions/hybriddelay_pharmacokinetics.md",
    "solutions/dae_double_pendulum.md",
    "solutions/acausal_circuit.md",
    "solutions/performance_pde.md",
    "solutions/gsa_henon_heiles.md",
    "solutions/neural_sde.md",
    "solutions/dc_motor_control.md"]]
